version: '3'
services:
  db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: hbnb_dev_db
      ports:
        - "3307:3306"
  console:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     RUN_MODE: dev
     DB_HOST: database
     DB_USER: root
     DB_PASSWORD: root
     DB_PORT: 3306
    depends_on:
       - db
    links:
      - "db:database"
volumes:
    db_data:
